### PR TITLE
docs: updating the readme with some of the cmake flags

### PR DESCRIPTION
**Pull request by muffins**
Summary:

This updates the readme a bit with some of the flags needed to put
together packages.

### CODE REVIEW

**Review by directionless — DISMISSED** [review]

**Comment by theopolis** [comment]
Alternatively, we might want to have the readme only include a link to the osquery read the docs packaging page.

This way we maintain a single place for documentation.

**Comment by muffins** [comment]
@theopolis sure, do you have a link to where those are? [This](https://osquery.readthedocs.io/en/stable/development/building/#on-windows) link looks dated, and doesn't match the current state of building custom packages on Windows.

Maybe a better solution here, as you're eluding to, is updating those docs with the correct flow yeah?

**Comment by theopolis** [comment]
I was referring to those. I thought they were up to date. :)

But yes, if we focus on a single place we can keep those fresh and accurate. I think that link is the most likely place people will look.

So then the readme here can just be a sentence:

Please refer to $LINK.

**Review by theopolis — APPROVED** [review]

**Comment by theopolis** [comment]
I sort of hijacked this and applied what we were discussing. Can you let me know how you feel about it / provide feedback?

**Comment by muffins** [comment]
@theopolis it lgtm. I have on my "todo" list to port the notes I've got for generating the package upstream. I'm happy to do it, but if someone beats me to it no worries :)

**Pull request merged**
